dist: xenial
language: cpp
compiler: g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - lcov

before_install:
  - export CC=gcc-8
  - export CXX=g++-8

install:
  - sudo add-apt-repository -y ppa:snaipewastaken/ppa
  - sudo apt-get update
  - sudo apt-get -y install criterion-dev

script:
  - cmake . -DOPENZIA_TESTS=TRUE -DOPENZIA_COVERAGE=TRUE
  - cmake --build .
  - ./openZiaTests

after_success:
  - bash <(curl -s https://codecov.io/bash)