dist: xenial
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - gcov
      - lcov

before_install:
  - sudo add-apt-repository -y ppa:snaipewastaken/ppa
  - sudo apt-get update
  - sudo apt-get -y install criterion-dev

script:
  - export CC=gcc-8
  - export CXX=g++-8
  - ./run_tests.sh

after_success:
  - ./upload_coverage.sh