dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - gcovr
      - lcov

before_install:
  - sudo add-apt-repository -y ppa:snaipewastaken/ppa
  - sudo apt-get update
  - sudo apt-get -y install criterion-dev

script:
  - export CC=gcc-8
  - export CXX=g++-8
  - mkdir Build && cd Build && cmake .. && make

after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"